window.WC26_HISTORY = [
  { year: 1930, champion: "Uruguay", runnerUp: "Argentina", host: "Uruguay", score: "4-2", flag: "Uruguay.png" },
  { year: 1934, champion: "Italia", runnerUp: "Checoslovaquia", host: "Italia", score: "2-1", flag: "Italia.png" },
  { year: 1938, champion: "Italia", runnerUp: "Hungría", host: "Francia", score: "4-2", flag: "Italia.png" },
  { year: 1950, champion: "Uruguay", runnerUp: "Brasil", host: "Brasil", score: "2-1", flag: "Uruguay.png" },
  { year: 1954, champion: "Alemania", runnerUp: "Hungría", host: "Suiza", score: "3-2", flag: "Alemania.png" },
  { year: 1958, champion: "Brasil", runnerUp: "Suecia", host: "Suecia", score: "5-2", flag: "Brasil.png" },
  { year: 1962, champion: "Brasil", runnerUp: "Checoslovaquia", host: "Chile", score: "3-1", flag: "Brasil.png" },
  { year: 1966, champion: "Inglaterra", runnerUp: "Alemania", host: "Inglaterra", score: "4-2", flag: "Inglaterra.png" },
  { year: 1970, champion: "Brasil", runnerUp: "Italia", host: "México", score: "4-1", flag: "Brasil.png" },
  { year: 1974, champion: "Alemania", runnerUp: "Países Bajos", host: "Alemania", score: "2-1", flag: "Alemania.png" },
  { year: 1978, champion: "Argentina", runnerUp: "Países Bajos", host: "Argentina", score: "3-1", flag: "Argentina.png" },
  { year: 1982, champion: "Italia", runnerUp: "Alemania", host: "España", score: "3-1", flag: "Italia.png" },
  { year: 1986, champion: "Argentina", runnerUp: "Alemania", host: "México", score: "3-2", flag: "Argentina.png" },
  { year: 1990, champion: "Alemania", runnerUp: "Argentina", host: "Italia", score: "1-0", flag: "Alemania.png" },
  { year: 1994, champion: "Brasil", runnerUp: "Italia", host: "Estados Unidos", score: "0-0 (3-2 p)", flag: "Brasil.png" },
  { year: 1998, champion: "Francia", runnerUp: "Brasil", host: "Francia", score: "3-0", flag: "Francia.png" },
  { year: 2002, champion: "Brasil", runnerUp: "Alemania", host: "Corea-Japón", score: "2-0", flag: "Brasil.png" },
  { year: 2006, champion: "Italia", runnerUp: "Francia", host: "Alemania", score: "1-1 (5-3 p)", flag: "Italia.png" },
  { year: 2010, champion: "España", runnerUp: "Países Bajos", host: "Sudáfrica", score: "1-0", flag: "España.png" },
  { year: 2014, champion: "Alemania", runnerUp: "Argentina", host: "Brasil", score: "1-0", flag: "Alemania.png" },
  { year: 2018, champion: "Francia", runnerUp: "Croacia", host: "Rusia", score: "4-2", flag: "Francia.png" },
  { year: 2022, champion: "Argentina", runnerUp: "Francia", host: "Qatar", score: "3-3 (4-2 p)", flag: "Argentina.png" }
];